CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_NEWLIB_LIBC=y
CONFIG_PWM=y
CONFIG_PWM_MCUX_TPM=n
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_PINCTRL=y
CONFIG_PWM_LOG_LEVEL_DBG=n
CONFIG_DYNAMIC_INTERRUPTS=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
